install:
  npm install

build: install
  npm run build

watch:
  npm run watch

test:
  deno test --allow-env test/*.test.ts

update-deps:
  npx npm-check-updates -u

apex-install:
  npm run devbuild

clean:
  rm -rf packages/*/node_modules
  rm -rf node_modules

